# Generated by Django 5.1.1 on 2025-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uloha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('hotova', models.BooleanField(default=False)),
                ('vytvorena', models.DateTimeField(auto_now_add=True)),
                ('termin', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
